version: 2.1
orbs:
  sfdx: circleci/salesforce-sfdx@2.1.1
jobs:
  authenticate:
    executor: sfdx/default
    steps:
      - sfdx/install
      - run:
          name: Check Auth List
          command: |
            sfdx auth:jwt:grant -u edgar.drummer1993@curious-goat-447951.com -f $SFDX_JWT_KEY -i $SFDX_CONSUMER_KEY
            sfdx force:org:list
workflows:
  workflow: 
    jobs:
      - authenticate