version: 2.1
  orbs:
    apex: circleci/salesforce-apex@x.y
  jobs:
    install_authenticate:
      docker:
        - image: cimg/node:14.5
      steps:
        - checkout
        - apex/setup:
           defaultusername: edgar.drummer1993@curious-goat-447951.com
        - run:
            name: Run your SFDX commands here
            command: sfdx --help
